// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwytqrslpaxltleohrvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3eXRxcnNscGF4bHRsZW9ocnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTc0NTcsImV4cCI6MjA2MjI3MzQ1N30.NLSU7AQ6nUZUkVrux0noE1Ur0tj4lQuxGsaSXNLtKIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);